---
title: "p8105_hw6_yw3608"
author: "Yuxuan Wang"
date: "12/2/2021"
output: github_document
---
# Problem 1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


**Prepare data,and check if missing data exist and drop na**
```{r,warning=FALSE,message = FALSE}
bw_df = 
  read_csv('data/birthweight.csv') %>% 
  drop_na()
```


**clean data, mutate several variables to factors,change level's name and show the data**
```{r}
bw_clean = 
  bw_df %>% 
  mutate(
    babysex = as.factor(babysex),
    father_race = as.factor(frace),
    malform = as.factor(malform),
    mother_race = as.factor(mrace)
  )  %>%
  mutate(
    babysex = recode(babysex, "1" = "male", "2" = "female"),
    father_race = recode(father_race, "1" = "white", "2" = "black", "3" = "asian", "4" = "puertorican", "8" = "other", "9" = "unknown"), 
    malform = recode(malform, "0" = "absense", "1" = "present"),
    mother_race = recode(mother_race, "1" = "white", "2" = "black", "3" = "asian", "4" = "puertorican", "8" =   "other")
    ) 
 
head(bw_clean ) %>% 
knitr::kable()
```

